name: aaxep
description: Moving made Simple
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  anchored_popups: ^0.1.0
  animate_do: ^2.0.0
  animated_text_kit: ^4.2.1
  animations: ^2.0.1
  auto_size_text: ^3.0.0-nullsafety.0
  badges: ^2.0.1
  bitsdojo_window: ^0.1.0+1
  bloc_pattern: ^3.0.0
  bottom_navy_bar: ^6.0.0
  cached_network_image: ^3.1.0
  cloudinary_public: ^0.8.0
  concentric_transition: ^1.0.1+1
  context_menus: ^0.1.0+5
  cupertino_icons: ^1.0.2
  darq: ^1.0.0-dev.3
  desktop_window: ^0.4.0
  dio: ^4.0.0
  dotted_border: ^2.0.0-nullsafety.0
  easy_localization: ^3.0.0
  email_validator: ^2.0.1
  enum_to_string: ^2.0.0-nullsafety.1
  file_selector_linux: ^0.0.2
  file_selector_macos: ^0.0.4
  file_selector_web: ^0.8.1
  file_selector_windows: ^0.0.2
  file_selector: ^0.8.2
  fl_chart: ^0.40.0
  flextras: ^0.0.1
  flutter_bloc: ^7.2.0
  flutter_blurhash: ^0.6.0
  flutter_form_builder: ^6.1.0
  flutter_lorem: ^2.0.0
  flutter_native_splash: ^1.2.3
  flutter_svg: ^0.22.0
  flutter_typeahead: ^3.2.1
  font_awesome_flutter: ^9.1.0
  form_builder_file_picker: ^1.1.0  
  form_builder_phone_field: ^0.3.0
  forme: ^2.5.3+1
  geolocator: ^7.6.0
  get: ^4.3.8
  google_fonts: ^2.1.0
  image_picker: ^0.8.0+4
  image_size_getter: ^1.0.0
  internationalization: ^3.1.0
  intro_slider: ^3.0.2
  local_auth: ^1.1.7
  lottie: ^1.1.0
  multi_image_picker: ^4.8.00
  package_info: ^2.0.2
  path_provider: ^2.0.1
  provider: ^6.0.0
  qr_flutter: ^4.0.0
  random_color: ^1.0.6-nullsafety
  rxdart: ^0.27.2
  share: ^2.0.1
  shared_preferences: ^2.0.4
  shimmer: ^2.0.0
  sized_context: ^1.0.0+1
  statsfl: ^2.0.1+1
  supercharged: ^2.0.0
  system_info: ^1.0.0
  timeago: ^3.0.2
  universal_platform: ^1.0.0-nullsafety
  url_launcher: ^6.0.2
  uuid: ^3.0.1
  visibility_detector: ^0.2.0-nullsafety.1

  # FIREBASE
  firedart: ^0.9.0+1
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1

dev_dependencies:
  # sample build cmd
  # flutter pub run build_runner build --delete-conflicting-outputs
  flutter_driver:
    sdk: flutter
  
  test: any
  flutter_test:
    sdk: flutter
  
  build_runner:
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^1.0.0
  freezed_annotation: ^0.14.1
  freezed: ^0.14.1
  json_serializable:
  msix: ^2.1.1

msix_config:
  display_name: AAxep
  publisher_display_name: gskinner, inc
  identity_name: 56347gskinner-xboxapps.FlutterFolio
  msix_version: 1.1.0.0
  start_menu_icon_path: ./source-assets/app-flutter-folio.png
  tile_icon_path: ./source-assets/app-flutter-folio.png
  publisher: CN=8BC7C029-E8A6-4A58-BB90-CCCBD93A99FD

flutter_icons:
  android: true
  ios: true
  image_path: source-assets/app-flutter-folio.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/emoji/
    - assets/images/logos/
    - assets/images/landing_page/

  fonts:
    - family: Fraunces
      fonts:
        - asset: assets/fonts/Fraunces_72pt-SemiBold.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
    - family: AlfaSlabOne
      fonts:
        - asset: assets/fonts/scraps/AlfaSlabOne-Regular.ttf
    - family: Amiri
      fonts:
        - asset: assets/fonts/scraps/Amiri-Regular.ttf
    - family: Caveat
      fonts:
        - asset: assets/fonts/scraps/Caveat-Medium.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/scraps/Lato-Regular.ttf
    - family: Mali
      fonts:
        - asset: assets/fonts/scraps/Mali-Medium.ttf
    - family: PathwayGothicOne
      fonts:
        - asset: assets/fonts/scraps/PathwayGothicOne-Regular.ttf
