// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDWEhR72iFdIGmR29iM8nHFv0Osf8pRIo',
    appId: '1:748712014583:web:05717cd0cfb6f8a3eb59f2',
    messagingSenderId: '748712014583',
    projectId: 'aaxepr',
    authDomain: 'aaxepr.firebaseapp.com',
    databaseURL: 'https://aaxepr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aaxepr.appspot.com',
    measurementId: 'G-EVHXDT1JB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB23Bc577iwGpxCHlkZCHM32YC0L3QxDzo',
    appId: '1:748712014583:android:2d58ef09deb4a529eb59f2',
    messagingSenderId: '748712014583',
    projectId: 'aaxepr',
    databaseURL: 'https://aaxepr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aaxepr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2eiji9JkbzSyr2orqe0rBWw-dpLCPP1w',
    appId: '1:748712014583:ios:ff5e6915de0cd2e7eb59f2',
    messagingSenderId: '748712014583',
    projectId: 'aaxepr',
    databaseURL: 'https://aaxepr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aaxepr.appspot.com',
    iosClientId: '748712014583-kmgvl2jk95jofssspfnh6lqp0thpkul4.apps.googleusercontent.com',
    iosBundleId: 'com.example.aaxep',
  );
}
